### ISSUE TITLE
How to configure Guild Checking?

### ISSUE THREAD

**Issue by KaratekHD** [wadahiro/keycloak-discord#24] opened 2022-08-15 10:20 UTC
From what I understand from the README it appears there is an option for only allowing members of certain guilds to log in into Keycloak using this Provider.
However, I can't find the option to specify the guilds allowed:
![image](https://user-images.githubusercontent.com/38097062/184618907-208b78df-b06c-458c-ad78-9eaef7d100c7.png)

Could you please point me in the right direction on where I can configure this feature?
Thank you!

**Comment by shibacomputer** [comment] 2022-09-21 17:54
Also having this issue!

**Comment by wadahiro** [comment] 2022-11-04 04:45
@KaratekHD @shibacomputer 

Sorry for the late response.
This problem is due to the use of the new admin console.
Unfortunately, this extension is not compatible with the new admin console.

It can be configured by setting `--features-disabled=admin2 ` when Keycloak is started, or by setting `keycloak` to "Admin console theme" in the master realm's theme settings and reverting to the old admin console.

I will try to implement the new admin console support. Thanks for the feedback!

**Comment by wadahiro** [comment] 2022-11-04 05:55
> I will try to implement the new admin console support.

Unfortunately, even the latest Keycloak v20 does not support custom provider settings in the new admin console.

https://github.com/keycloak/keycloak-ui/issues/3696

We need to wait first for the new admin console side to be fixed.

**Comment by shibacomputer** [comment] 2022-11-04 16:59
Thanks for following up @wadahiro, I appreciate it! I will keep an eye on https://github.com/keycloak/keycloak-ui/issues/3696 also

**Comment by wadahiro** [comment] 2023-04-03 00:40
Although https://github.com/keycloak/keycloak/issues/17958 was closed, now the issue is discussed in https://github.com/keycloak/keycloak/issues/15344.

**Comment by chris-sanders** [comment] 2023-07-15 20:47
I notice both of the linked issues are now closed. I've been unable to get version 21.1.2 to startup with the suggested them or admin2 disables. The theme causes an internal error and disabling admin2 seems to just turn admin off all together.

Is this now possible with the above issues closed or is there any way I can manually configure this even without display in the UI? I'm running the bitnami chart if that matters at all.

**Comment by wadahiro** [comment] 2023-08-11 06:04
I confirmed the problem was resolved by the following pull requests:

- https://github.com/keycloak/keycloak/pull/21097
- https://github.com/keycloak/keycloak/pull/21320

I created a pull request for support keycloak 22 and the new admin console: #37

**Closed** 2023-08-11 06:05 UTC
